### PR TITLE
I like the splash

### LINKED ISSUE #25: Splashscreen
I would like to work on the Configuration of splash screen according to the design guidelines present in PR #15

### PR DESCRIPTION
**Pull request by abhinavsri360**
### Description
Configured the splash screen close to as described in issue #12 The screenshot is provided below. Also, @himanshusharma89 , @ishandeveloper are there ways to create clock and a lamp on splash screen apart from using images? I wasn't able to figure anything similar 🤔 

Fixes # [ISSUE]
Closes #25 

### How Has This Been Tested?
Compiling and running the application on my phone i.e., an android device.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged
- [x] My changes generate no new warnings

Screenshot::
Screenshot_20200630-162415

### CODE REVIEW

**Comment by himanshusharma89** [comment]
Hey, you can try to change the gradient location so that it would look much better (like 45 degrees). Also, you can create anything on this splash screen because it is a widget.
And you can ignore pushing the pubspec.lock file, it changes up to the user's device.

**Comment by abhinavsri360** [comment]
Sure, I'll change the gradient, but it looks pinker at 45 degrees what should I do?. Well, as far as creation is concerned can you tell me how to add, like I've never done that before. Sure, I'll ignore pushing pubspec.lock

**Comment by CheshtaK** [comment]
Hey @abhinavsri360! Refer [this](https://github.com/afgprogrammer/Flutter-Login-Page-UI) for the images and animation. Let's try and stick to the proposed design.

**Comment by abhinavsri360** [comment]
Thanks, @CheshtaK for references.

**Pull request closed without merging**
