### PR TITLE
more genres added

### LINKED ISSUE #11: Add more book genres
**Is your feature request related to a problem? Please describe.**
We must add more book genres, anyone doing so can refer to the link: https://www.oprahmag.com/entertainment/books/a29576863/types-of-book-genres/ and therefore, add more genres as per understanding, but in my opinion, I find these appropriate to be added.

**Describe the solution you'd like**
Genres to be added

**Additional context**
I would like to work on this feature.

### PR DESCRIPTION
**Pull request by abhinavsri360**
### Description
1. Added more genres for the feasibility of users.
2. String updated
3. Pictures added along
4. pubspec.yaml updated to load all resources present in assets directory

Fixes # [ISSUE]
Closes #11 
### How Has This Been Tested?
Screenshots::
Screenshot_20200620-182702
Screenshot_20200620-182646
Screenshot_20200620-182654

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged
- [x] My changes generate no new warnings
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning)

### CODE REVIEW

**Review by CheshtaK — CHANGES_REQUESTED** [review]
@abhinavsri360 some of the text are not visible on top of the images. Could add opacity to the images? Refer the `colorBlendMode` [here](https://api.flutter.dev/flutter/widgets/Opacity-class.html). There a lot of other options too.

**Comment by abhinavsri360** [comment]
Screenshot_20200620-225007
I used text styling and now it is visible on all pictures. I think adding opacity will lead to check and define it for different images. Whereas, creating styling can be feasible. Please let me know your views.
References: https://api.flutter.dev/flutter/painting/TextStyle-class.html#painting.TextStyle.6

**Comment by abhinavsri360** [comment]
Waiting for review @CheshtaK @himanshusharma89

**Comment by himanshusharma89** [comment]
> Waiting for review @CheshtaK @himanshusharma89

It looks good to me.

**Pull request merged**
